[package]
name = "evm-abi"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "example"
path = "example/main.rs"

[dependencies]
alloy-sol-types = {version = "1.3.1", features = ["json"]}
alloy-contract = "1.0.27"
alloy-primitives = "1.3.1"
